/*
Team Table Syntax
 */
package softwareengineeringproject;

/**
 *
 * @author 23657952
 */
public class teamTable extends javax.swing.JFrame {

    /**
     * Creates new form teamTable
     */
    public teamTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelT1S1 = new javax.swing.JLabel();
        jLabelT1S2 = new javax.swing.JLabel();
        jLabelT1S3 = new javax.swing.JLabel();
        jLabelT1S4 = new javax.swing.JLabel();
        jLabelT1S5 = new javax.swing.JLabel();
        jLabelT1S6 = new javax.swing.JLabel();
        jLabelT2S1 = new javax.swing.JLabel();
        jLabelT2S2 = new javax.swing.JLabel();
        jLabelT2S3 = new javax.swing.JLabel();
        jLabelT2S4 = new javax.swing.JLabel();
        jLabelT2S5 = new javax.swing.JLabel();
        jLabelT2S6 = new javax.swing.JLabel();
        jLabelT3S1 = new javax.swing.JLabel();
        jLabelT3S2 = new javax.swing.JLabel();
        jLabelT3S3 = new javax.swing.JLabel();
        jLabelT3S4 = new javax.swing.JLabel();
        jLabelT3S5 = new javax.swing.JLabel();
        jLabelT3S6 = new javax.swing.JLabel();
        jLabelT4S1 = new javax.swing.JLabel();
        jLabelT4S2 = new javax.swing.JLabel();
        jLabelT4S3 = new javax.swing.JLabel();
        jLabelT4S4 = new javax.swing.JLabel();
        jLabelT4S5 = new javax.swing.JLabel();
        jLabelT4S6 = new javax.swing.JLabel();
        jLabelT5S1 = new javax.swing.JLabel();
        jLabelT5S2 = new javax.swing.JLabel();
        jLabelT5S3 = new javax.swing.JLabel();
        jLabelT5S4 = new javax.swing.JLabel();
        jLabelT5S5 = new javax.swing.JLabel();
        jLabelT5S6 = new javax.swing.JLabel();
        jLabelT6S1 = new javax.swing.JLabel();
        jLabelT6S2 = new javax.swing.JLabel();
        jLabelT6S3 = new javax.swing.JLabel();
        jLabelT6S4 = new javax.swing.JLabel();
        jLabelT6S5 = new javax.swing.JLabel();
        jLabelT6S6 = new javax.swing.JLabel();
        jLabelT7S1 = new javax.swing.JLabel();
        jLabelT7S2 = new javax.swing.JLabel();
        jLabelT7S3 = new javax.swing.JLabel();
        jLabelT7S4 = new javax.swing.JLabel();
        jLabelT7S5 = new javax.swing.JLabel();
        jLabelT7S6 = new javax.swing.JLabel();
        jLabelT8S1 = new javax.swing.JLabel();
        jLabelT9S1 = new javax.swing.JLabel();
        jLabelT10S1 = new javax.swing.JLabel();
        jLabelT11S1 = new javax.swing.JLabel();
        jLabelT12S1 = new javax.swing.JLabel();
        jLabelT13S1 = new javax.swing.JLabel();
        jLabelT14S1 = new javax.swing.JLabel();
        jLabelT15S1 = new javax.swing.JLabel();
        jLabelT15S2 = new javax.swing.JLabel();
        jLabelT15S3 = new javax.swing.JLabel();
        jLabelT15S4 = new javax.swing.JLabel();
        jLabelT15S5 = new javax.swing.JLabel();
        jLabelT15S6 = new javax.swing.JLabel();
        jLabelT14S2 = new javax.swing.JLabel();
        jLabelT13S2 = new javax.swing.JLabel();
        jLabelT12S2 = new javax.swing.JLabel();
        jLabelT11S2 = new javax.swing.JLabel();
        jLabelT10S2 = new javax.swing.JLabel();
        jLabelT9S2 = new javax.swing.JLabel();
        jLabelT8S2 = new javax.swing.JLabel();
        jLabelT8S3 = new javax.swing.JLabel();
        jLabelT8S4 = new javax.swing.JLabel();
        jLabelT8S5 = new javax.swing.JLabel();
        jLabelT8S6 = new javax.swing.JLabel();
        jLabelT9S3 = new javax.swing.JLabel();
        jLabelT10S3 = new javax.swing.JLabel();
        jLabelT11S3 = new javax.swing.JLabel();
        jLabelT12S3 = new javax.swing.JLabel();
        jLabelT13S3 = new javax.swing.JLabel();
        jLabelT14S3 = new javax.swing.JLabel();
        jLabelT9S4 = new javax.swing.JLabel();
        jLabelT10S4 = new javax.swing.JLabel();
        jLabelT11S4 = new javax.swing.JLabel();
        jLabelT12S4 = new javax.swing.JLabel();
        jLabelT13S4 = new javax.swing.JLabel();
        jLabelT14S4 = new javax.swing.JLabel();
        jLabelT9S5 = new javax.swing.JLabel();
        jLabelT9S = new javax.swing.JLabel();
        jLabelT10S5 = new javax.swing.JLabel();
        jLabelT11S5 = new javax.swing.JLabel();
        jLabelT12S5 = new javax.swing.JLabel();
        jLabelT13S5 = new javax.swing.JLabel();
        jLabelT14S5 = new javax.swing.JLabel();
        jLabelT14S6 = new javax.swing.JLabel();
        jLabelT10S6 = new javax.swing.JLabel();
        jLabelT11S6 = new javax.swing.JLabel();
        jLabelT12S6 = new javax.swing.JLabel();
        jLabelT13S6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Team 1");

        jLabel9.setText("Team 2");

        jLabel10.setText("Team 3");

        jLabel11.setText("Team 4");

        jLabel12.setText("Team 5");

        jLabel13.setText("Team 6");

        jLabel14.setText("Team 7");

        jLabel15.setText("Team 8");

        jLabel16.setText("Team 9");

        jLabel17.setText("Team 10");

        jLabelT1S1.setText(mainWindow.teams[0].students[0].getName());

        jLabelT1S2.setText(mainWindow.teams[0].students[1].getName());

        jLabelT1S3.setText(mainWindow.teams[0].students[2].getName());

        jLabelT1S4.setText(mainWindow.teams[0].students[3].getName());

        jLabelT1S5.setText(mainWindow.teams[0].students[4].getName());

        jLabelT1S6.setText(mainWindow.teams[0].students[5].getName());

        jLabelT2S1.setText(mainWindow.teams[1].students[0].getName());

        jLabelT2S2.setText(mainWindow.teams[1].students[1].getName());

        jLabelT2S3.setText(mainWindow.teams[1].students[2].getName());

        jLabelT2S4.setText(mainWindow.teams[1].students[3].getName());

        jLabelT2S5.setText(mainWindow.teams[1].students[4].getName());

        jLabelT2S6.setText(mainWindow.teams[1].students[5].getName());

        jLabelT3S1.setText(mainWindow.teams[2].students[0].getName());

        jLabelT3S2.setText(mainWindow.teams[2].students[1].getName());

        jLabelT3S3.setText(mainWindow.teams[2].students[2].getName());

        jLabelT3S4.setText(mainWindow.teams[2].students[3].getName());

        jLabelT3S5.setText(mainWindow.teams[2].students[4].getName());

        jLabelT3S6.setText(mainWindow.teams[2].students[5].getName());

        jLabelT4S1.setText(mainWindow.teams[3].students[0].getName());

        jLabelT4S2.setText(mainWindow.teams[3].students[1].getName());

        jLabelT4S3.setText(mainWindow.teams[3].students[2].getName());

        jLabelT4S4.setText(mainWindow.teams[3].students[3].getName());

        jLabelT4S5.setText(mainWindow.teams[3].students[4].getName());

        jLabelT4S6.setText(mainWindow.teams[3].students[5].getName());

        jLabelT5S1.setText(mainWindow.teams[4].students[0].getName());

        jLabelT5S2.setText(mainWindow.teams[4].students[1].getName());

        jLabelT5S3.setText(mainWindow.teams[4].students[2].getName());

        jLabelT5S4.setText(mainWindow.teams[4].students[3].getName());

        jLabelT5S5.setText(mainWindow.teams[4].students[4].getName());

        jLabelT5S6.setText(mainWindow.teams[4].students[5].getName());

        jLabelT6S1.setText(mainWindow.teams[5].students[0].getName());

        jLabelT6S2.setText(mainWindow.teams[5].students[1].getName());

        jLabelT6S3.setText(mainWindow.teams[5].students[2].getName());

        jLabelT6S4.setText(mainWindow.teams[5].students[3].getName());

        jLabelT6S5.setText(mainWindow.teams[5].students[4].getName());

        jLabelT6S6.setText(mainWindow.teams[5].students[5].getName());

        jLabelT7S1.setText(mainWindow.teams[6].students[0].getName());

        jLabelT7S2.setText(mainWindow.teams[6].students[1].getName());

        jLabelT7S3.setText(mainWindow.teams[6].students[2].getName());

        jLabelT7S4.setText(mainWindow.teams[6].students[3].getName());

        jLabelT7S5.setText(mainWindow.teams[6].students[4].getName());

        jLabelT7S6.setText(mainWindow.teams[6].students[5].getName());

        jLabelT8S1.setText(mainWindow.teams[7].students[0].getName());

        jLabelT9S1.setText(mainWindow.teams[8].students[0].getName());

        jLabelT10S1.setText(mainWindow.teams[9].students[0].getName());

        jLabelT11S1.setText(mainWindow.team11Array[0]);

        jLabelT12S1.setText(mainWindow.team12Array[0]);

        jLabelT13S1.setText(mainWindow.team13Array[0]);

        jLabelT14S1.setText(mainWindow.team14Array[0]);

        jLabelT15S1.setText(mainWindow.team15Array[0]);

        jLabelT15S2.setText(mainWindow.team15Array[1]);

        jLabelT15S3.setText(mainWindow.team15Array[2]);

        jLabelT15S4.setText(mainWindow.team15Array[3]);

        jLabelT15S5.setText(mainWindow.team15Array[4]);

        jLabelT15S6.setText(mainWindow.team15Array[5]);

        jLabelT14S2.setText(mainWindow.team14Array[1]);

        jLabelT13S2.setText(mainWindow.team13Array[1]);

        jLabelT12S2.setText(mainWindow.team12Array[1]);

        jLabelT11S2.setText(mainWindow.team11Array[1]);

        jLabelT10S2.setText(mainWindow.teams[9].students[1].getName());

        jLabelT9S2.setText(mainWindow.teams[8].students[1].getName());

        jLabelT8S2.setText(mainWindow.teams[7].students[1].getName());

        jLabelT8S3.setText(mainWindow.teams[7].students[2].getName());

        jLabelT8S4.setText(mainWindow.teams[7].students[3].getName());

        jLabelT8S5.setText(mainWindow.teams[7].students[4].getName());

        jLabelT8S6.setText(mainWindow.teams[7].students[5].getName());

        jLabelT9S3.setText(mainWindow.teams[8].students[2].getName());

        jLabelT10S3.setText(mainWindow.teams[9].students[2].getName());

        jLabelT11S3.setText(mainWindow.team11Array[2]);

        jLabelT12S3.setText(mainWindow.team12Array[2]);

        jLabelT13S3.setText(mainWindow.team13Array[2]);

        jLabelT14S3.setText(mainWindow.team14Array[2]);

        jLabelT9S4.setText(mainWindow.teams[8].students[3].getName());

        jLabelT10S4.setText(mainWindow.teams[9].students[3].getName());

        jLabelT11S4.setText(mainWindow.team11Array[3]);

        jLabelT12S4.setText(mainWindow.team12Array[3]);

        jLabelT13S4.setText(mainWindow.team13Array[3]);

        jLabelT14S4.setText(mainWindow.team14Array[3]);

        jLabelT9S5.setText(mainWindow.teams[8].students[4].getName());

        jLabelT9S.setText(mainWindow.teams[8].students[5].getName());

        jLabelT10S5.setText(mainWindow.teams[9].students[4].getName());

        jLabelT11S5.setText(mainWindow.team11Array[4]);

        jLabelT12S5.setText(mainWindow.team12Array[5]);

        jLabelT13S5.setText(mainWindow.team13Array[4]);

        jLabelT14S5.setText(mainWindow.team14Array[4]);

        jLabelT14S6.setText(mainWindow.team14Array[5]);

        jLabelT10S6.setText(mainWindow.teams[9].students[5].getName());

        jLabelT11S6.setText(mainWindow.team11Array[5]);

        jLabelT12S6.setText(mainWindow.team12Array[5]);

        jLabelT13S6.setText(mainWindow.team13Array[5]);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelT1S1)
                                .addGap(64, 64, 64)
                                .addComponent(jLabelT1S2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelT3S1)
                                    .addComponent(jLabelT2S1)
                                    .addComponent(jLabelT4S1)
                                    .addComponent(jLabelT5S1)
                                    .addComponent(jLabelT6S1)
                                    .addComponent(jLabelT7S1)
                                    .addComponent(jLabelT8S1)
                                    .addComponent(jLabelT9S1)
                                    .addComponent(jLabelT10S1)
                                    .addComponent(jLabelT11S1)
                                    .addComponent(jLabelT12S1)
                                    .addComponent(jLabelT13S1)
                                    .addComponent(jLabelT14S1)
                                    .addComponent(jLabelT15S1))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelT2S2)
                                    .addComponent(jLabelT3S2)
                                    .addComponent(jLabelT4S2)
                                    .addComponent(jLabelT5S2)
                                    .addComponent(jLabelT6S2)
                                    .addComponent(jLabelT7S2)
                                    .addComponent(jLabelT15S2)
                                    .addComponent(jLabelT14S2)
                                    .addComponent(jLabelT13S2)
                                    .addComponent(jLabelT12S2)
                                    .addComponent(jLabelT11S2)
                                    .addComponent(jLabelT10S2)
                                    .addComponent(jLabelT9S2)
                                    .addComponent(jLabelT8S2)))))
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelT1S3)
                    .addComponent(jLabelT2S3)
                    .addComponent(jLabelT3S3)
                    .addComponent(jLabelT4S3)
                    .addComponent(jLabelT5S3)
                    .addComponent(jLabelT6S3)
                    .addComponent(jLabelT7S3)
                    .addComponent(jLabelT15S3)
                    .addComponent(jLabelT8S3)
                    .addComponent(jLabelT9S3)
                    .addComponent(jLabelT10S3)
                    .addComponent(jLabelT11S3)
                    .addComponent(jLabelT12S3)
                    .addComponent(jLabelT13S3)
                    .addComponent(jLabelT14S3))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelT1S4)
                        .addComponent(jLabelT2S4)
                        .addComponent(jLabelT3S4)
                        .addComponent(jLabelT4S4)
                        .addComponent(jLabelT5S4)
                        .addComponent(jLabelT6S4)
                        .addComponent(jLabelT7S4)
                        .addComponent(jLabelT15S4)
                        .addComponent(jLabelT8S4)
                        .addComponent(jLabelT9S4)
                        .addComponent(jLabelT10S4)
                        .addComponent(jLabelT11S4)
                        .addComponent(jLabelT12S4)
                        .addComponent(jLabelT13S4))
                    .addComponent(jLabelT14S4))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelT10S5)
                    .addComponent(jLabelT11S5)
                    .addComponent(jLabelT12S5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT1S5)
                                .addComponent(jLabelT2S5)
                                .addComponent(jLabelT3S5)
                                .addComponent(jLabelT4S5)
                                .addComponent(jLabelT5S5)
                                .addComponent(jLabelT6S5)
                                .addComponent(jLabelT7S5)
                                .addComponent(jLabelT15S5)
                                .addComponent(jLabelT8S5))
                            .addComponent(jLabelT9S5)
                            .addComponent(jLabelT13S5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelT1S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT2S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT3S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT4S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT5S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT6S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT7S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT15S6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelT8S6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelT9S)
                            .addComponent(jLabelT10S6)
                            .addComponent(jLabelT11S6)
                            .addComponent(jLabelT12S6)
                            .addComponent(jLabelT13S6)
                            .addComponent(jLabelT14S6)))
                    .addComponent(jLabelT14S5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelT1S1)
                    .addComponent(jLabelT1S2)
                    .addComponent(jLabelT1S3)
                    .addComponent(jLabelT1S4)
                    .addComponent(jLabelT1S5)
                    .addComponent(jLabelT1S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelT2S1)
                    .addComponent(jLabelT2S2)
                    .addComponent(jLabelT2S3)
                    .addComponent(jLabelT2S4)
                    .addComponent(jLabelT2S5)
                    .addComponent(jLabelT2S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelT3S1)
                    .addComponent(jLabelT3S2)
                    .addComponent(jLabelT3S3)
                    .addComponent(jLabelT3S4)
                    .addComponent(jLabelT3S5)
                    .addComponent(jLabelT3S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelT4S1)
                    .addComponent(jLabelT4S2)
                    .addComponent(jLabelT4S3)
                    .addComponent(jLabelT4S4)
                    .addComponent(jLabelT4S5)
                    .addComponent(jLabelT4S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelT5S1)
                    .addComponent(jLabelT5S2)
                    .addComponent(jLabelT5S3)
                    .addComponent(jLabelT5S4)
                    .addComponent(jLabelT5S5)
                    .addComponent(jLabelT5S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelT6S1)
                    .addComponent(jLabelT6S2)
                    .addComponent(jLabelT6S3)
                    .addComponent(jLabelT6S4)
                    .addComponent(jLabelT6S5)
                    .addComponent(jLabelT6S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelT7S1)
                    .addComponent(jLabelT7S2)
                    .addComponent(jLabelT7S3)
                    .addComponent(jLabelT7S4)
                    .addComponent(jLabelT7S5)
                    .addComponent(jLabelT7S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelT8S1)
                    .addComponent(jLabelT8S2)
                    .addComponent(jLabelT8S3)
                    .addComponent(jLabelT8S4)
                    .addComponent(jLabelT8S5)
                    .addComponent(jLabelT8S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelT9S1)
                    .addComponent(jLabelT9S2)
                    .addComponent(jLabelT9S3)
                    .addComponent(jLabelT9S4)
                    .addComponent(jLabelT9S5)
                    .addComponent(jLabelT9S))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelT10S1)
                    .addComponent(jLabelT10S2)
                    .addComponent(jLabelT10S3)
                    .addComponent(jLabelT10S4)
                    .addComponent(jLabelT10S5)
                    .addComponent(jLabelT10S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT11S1)
                    .addComponent(jLabelT11S2)
                    .addComponent(jLabelT11S3)
                    .addComponent(jLabelT11S4)
                    .addComponent(jLabelT11S5)
                    .addComponent(jLabelT11S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT12S1)
                    .addComponent(jLabelT12S2)
                    .addComponent(jLabelT12S3)
                    .addComponent(jLabelT12S4)
                    .addComponent(jLabelT12S5)
                    .addComponent(jLabelT12S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT13S1)
                    .addComponent(jLabelT13S2)
                    .addComponent(jLabelT13S3)
                    .addComponent(jLabelT13S4)
                    .addComponent(jLabelT13S5)
                    .addComponent(jLabelT13S6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelT14S6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelT14S1)
                        .addComponent(jLabelT14S2)
                        .addComponent(jLabelT14S3)
                        .addComponent(jLabelT14S4)
                        .addComponent(jLabelT14S5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT15S1)
                    .addComponent(jLabelT15S2)
                    .addComponent(jLabelT15S3)
                    .addComponent(jLabelT15S4)
                    .addComponent(jLabelT15S5)
                    .addComponent(jLabelT15S6))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText("Team");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    
        /* Create and display the form */
    public static void createFrame(){    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teamTable().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelT10S1;
    private javax.swing.JLabel jLabelT10S2;
    private javax.swing.JLabel jLabelT10S3;
    private javax.swing.JLabel jLabelT10S4;
    private javax.swing.JLabel jLabelT10S5;
    private javax.swing.JLabel jLabelT10S6;
    private javax.swing.JLabel jLabelT11S1;
    private javax.swing.JLabel jLabelT11S2;
    private javax.swing.JLabel jLabelT11S3;
    private javax.swing.JLabel jLabelT11S4;
    private javax.swing.JLabel jLabelT11S5;
    private javax.swing.JLabel jLabelT11S6;
    private javax.swing.JLabel jLabelT12S1;
    private javax.swing.JLabel jLabelT12S2;
    private javax.swing.JLabel jLabelT12S3;
    private javax.swing.JLabel jLabelT12S4;
    private javax.swing.JLabel jLabelT12S5;
    private javax.swing.JLabel jLabelT12S6;
    private javax.swing.JLabel jLabelT13S1;
    private javax.swing.JLabel jLabelT13S2;
    private javax.swing.JLabel jLabelT13S3;
    private javax.swing.JLabel jLabelT13S4;
    private javax.swing.JLabel jLabelT13S5;
    private javax.swing.JLabel jLabelT13S6;
    private javax.swing.JLabel jLabelT14S1;
    private javax.swing.JLabel jLabelT14S2;
    private javax.swing.JLabel jLabelT14S3;
    private javax.swing.JLabel jLabelT14S4;
    private javax.swing.JLabel jLabelT14S5;
    private javax.swing.JLabel jLabelT14S6;
    private javax.swing.JLabel jLabelT15S1;
    private javax.swing.JLabel jLabelT15S2;
    private javax.swing.JLabel jLabelT15S3;
    private javax.swing.JLabel jLabelT15S4;
    private javax.swing.JLabel jLabelT15S5;
    private javax.swing.JLabel jLabelT15S6;
    private javax.swing.JLabel jLabelT1S1;
    private javax.swing.JLabel jLabelT1S2;
    private javax.swing.JLabel jLabelT1S3;
    private javax.swing.JLabel jLabelT1S4;
    private javax.swing.JLabel jLabelT1S5;
    private javax.swing.JLabel jLabelT1S6;
    private javax.swing.JLabel jLabelT2S1;
    private javax.swing.JLabel jLabelT2S2;
    private javax.swing.JLabel jLabelT2S3;
    private javax.swing.JLabel jLabelT2S4;
    private javax.swing.JLabel jLabelT2S5;
    private javax.swing.JLabel jLabelT2S6;
    private javax.swing.JLabel jLabelT3S1;
    private javax.swing.JLabel jLabelT3S2;
    private javax.swing.JLabel jLabelT3S3;
    private javax.swing.JLabel jLabelT3S4;
    private javax.swing.JLabel jLabelT3S5;
    private javax.swing.JLabel jLabelT3S6;
    private javax.swing.JLabel jLabelT4S1;
    private javax.swing.JLabel jLabelT4S2;
    private javax.swing.JLabel jLabelT4S3;
    private javax.swing.JLabel jLabelT4S4;
    private javax.swing.JLabel jLabelT4S5;
    private javax.swing.JLabel jLabelT4S6;
    private javax.swing.JLabel jLabelT5S1;
    private javax.swing.JLabel jLabelT5S2;
    private javax.swing.JLabel jLabelT5S3;
    private javax.swing.JLabel jLabelT5S4;
    private javax.swing.JLabel jLabelT5S5;
    private javax.swing.JLabel jLabelT5S6;
    private javax.swing.JLabel jLabelT6S1;
    private javax.swing.JLabel jLabelT6S2;
    private javax.swing.JLabel jLabelT6S3;
    private javax.swing.JLabel jLabelT6S4;
    private javax.swing.JLabel jLabelT6S5;
    private javax.swing.JLabel jLabelT6S6;
    private javax.swing.JLabel jLabelT7S1;
    private javax.swing.JLabel jLabelT7S2;
    private javax.swing.JLabel jLabelT7S3;
    private javax.swing.JLabel jLabelT7S4;
    private javax.swing.JLabel jLabelT7S5;
    private javax.swing.JLabel jLabelT7S6;
    private javax.swing.JLabel jLabelT8S1;
    private javax.swing.JLabel jLabelT8S2;
    private javax.swing.JLabel jLabelT8S3;
    private javax.swing.JLabel jLabelT8S4;
    private javax.swing.JLabel jLabelT8S5;
    private javax.swing.JLabel jLabelT8S6;
    private javax.swing.JLabel jLabelT9S;
    private javax.swing.JLabel jLabelT9S1;
    private javax.swing.JLabel jLabelT9S2;
    private javax.swing.JLabel jLabelT9S3;
    private javax.swing.JLabel jLabelT9S4;
    private javax.swing.JLabel jLabelT9S5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
